name: CodeQL static test
on:
  workflow_call:
    inputs:
      languageJson: 
        description: 'Programming language selection [go, javascript, csharp, python, cpp, java]'
        required: true
        type: string
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - id: setVariables
        run: |
          echo "matrix=$input" >> "$GITHUB_OUTPUT"
        env:
          input: ${{ inputs.languageJson }}
  codeql:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        language: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.language }}
