name: Generate checkout workflow

on:
  push:
    paths:
     - 'manifest.json'

  workflow_dispatch:

jobs:
  Generate-checkout-workflow:
    runs-on: ubuntu-latest
    # Container need to run with bash shell for git-auto-commit-action
    defaults:
      run:
        shell: bash
    container: ghcr.io/${{ github.repository }}:latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GENERATE_WORKFLOW}}

      - name: Run script to generate workflow
        run: python generate_workflow.py
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate workflow
