name: Linter
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.py'
jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python2.7 & pip
        run: |
          sudo apt -y install python2.7
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          python2.7 get-pip.py

      - name: Install flake8 & plugins
        run: |
          pip install flake8==3.9.2 pep8-naming==0.12.1 flake8-builtins==1.5.3 flake8-comprehensions
          python2.7 -m pip list

      - name: Run Lint
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        # || true is for avoiding grep exit code 1 when there's no match
        run: |
          FILES_TO_SCAN=$(git diff --diff-filter=d --name-only origin/$GITHUB_BASE_REF | grep .py)
          flake8 --ignore=A003 --ignore-names "setUp,tearDown,[Ss]eq_*" --max-line-length 180 --tee --output-file report $FILES_TO_SCAN || EXIT_CODE=$?
          COMMENT_BODY=$(echo "## [Lint summary]($JOB_URL)")
          if [ $EXIT_CODE ]; then
            COMMENT_BODY+=$(echo -e "\n$(cat report)")
            cat report >> "$GITHUB_STEP_SUMMARY"
          else
            COMMENT_BODY+=$(echo -e "\nNo issues found! :partying_face:")
          fi
          gh pr comment $PR_NUMBER -b "$COMMENT_BODY"
          exit $EXIT_CODE
