name: build
on: 
  workflow_dispatch:
    inputs:
      is_dummy:
        type: string
        description: Dummy build?
        default: false
    
        
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - run: |
          echo "is_dummy(from inputs)=${{ inputs.is_dummy }}"
          $is_dummy = ${{ inputs.is_dummy }}
          echo "is_dummy=$(is_dummy)"
          $is_dummy.GetType()
          if ($is_dummy.Tolower() -eq "true") {
            $dummy_arg = "--dummy"
          }
          else {
            $dummy_arg = ""
          }
          "DUMMY_ARG=$dummy_arg" >> $env:GITHUB_ENV
          
      - run: |
          echo $env:DUMMY_ARG
