name: build
on: 
  workflow_dispatch:
    inputs:
      is_dummy:
        type: string
        description: Dummy build?
        default: false
    
        
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - run: |
          echo "input=${{ inputs.is_dummy }}"
          if ($is_dummy -ieq "true") 
          {
            $dummy_arg = "--dummy"
          }
          else 
          {
            $dummy_arg = "foo"
          }
          "DUMMY_ARG=$dummy_arg" >> $env:GITHUB_ENV
          
      - run: |
          echo ${{ env.DUMMY_ARG }}
