name: build
on: 
  workflow_dispatch:
    inputs:
      is_dummy:
        type: boolean
        description: Dummy build?
        default: false
    
        
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - run: |
          if (${{ inputs.is_dummy }}) {
            $dummy_arg = --dummy
          }
          else {
            $dummy_arg = ""
          }
          "DUMMY_ARG=$dummy_arg" >> $env:GITHUB_ENV
          
      - run: |
          echo $env:DUMMY_ARG
