name: build
on: 
  workflow_dispatch:
    inputs:
      is_dummy:
        type: boolean
        description: Dummy build?
        default: true
    
env:
#   runner_comfig: ${{ fromJSON(vars.RUNNER_CONF) }}
#   test_release_to_env: '{"true": "onprem", "false": "cloud"}'
#   runner_env: ${{ inputs.is_dummy == 'true' && 'onprem' || 'cloud' }}
  release_type: ${{ fromJSON('{"true":"test","false":"official"}')[inputs.is_dummy] }}
jobs:
  job1:
#     env:
#       platform: "${{ inputs.is_dummy == 'true' && 'onprem' || 'cloud' }}"
#       runner_conf: ${{ fromJSON(vars.RUNNER_CONF) }}
#     runs-on: ${{ fromJSON(vars.RUNNER_CONF)[inputs.is_dummy == 'true' && 'onprem' || 'cloud'].runs-on}}
    runs-on: windows-latest
    steps:
      - name: set output
        if: inputs.is_dummy
        uses: actions/checkout@v4
#         shell: bash
#         run: |
#           echo "hello"
#       - name: Foo
# #         if: env.runner_env == 'cloud'
#         run: |
#           echo "true"

        
        
        
        
        
#         run: |
#           echo "input=${{ inputs.is_dummy }}"
          
#           if [ "${{ inputs.is_dummy }}" = "true" ]; then
#               dummy_arg="--dummy"
#           else
#               dummy_arg="foo"
#           fi
          
#           echo "DUMMY_ARG=$dummy_arg" >> "$GITHUB_ENV"

#         run: |
#           echo "input=${{ inputs.is_dummy }}"
#           if (${{ inputs.is_dummy }} -ieq "true") 
#           {
#             $dummy_arg = "--dummy"
#           }
#           else 
#           {
#             $dummy_arg = "foo"
#           }
#           "DUMMY_ARG=$dummy_arg" >> $env:GITHUB_ENV
          
#       - run: |
#           echo ${{ env.DUMMY_ARG }}
