name: build
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run_id = " ${{ github.run_id }}
          echo "run_number = " ${{ github.run_number }}
          echo "run_attempt = " ${{ github.run_attempt }}
