name: build
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          
      - run: |
          pip list
          py -3 -E -m pip list
