name: build
on: 
  workflow_dispatch:
    inputs:
      build_config:
        type: string
        description: Build configuration
        default: foo
        
env:
  foo: configs.build.${{ inputs.build_config }}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $env:foo
