name: Print context
on:
  workflow_dispatch:

jobs:
  Print-Context:
    runs-on: ubuntu-latest
    steps:
      - name: Print to summary
        env:
          JOB_ID: ${{ github.job }}
        run: |
          echo $JOB_ID
          echo "Hello world $JOB_ID" >> "$GITHUB_STEP_SUMMARY"
      - name: Print the Github Context
        id: print-context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
