name: Release
on:
  workflow_dispatch:
  
jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          tag: v1.0.${{ github.run_number }}
        run: |
          gh release create "$tag" --generate-notes
