name: Release
on:
  workflow_dispatch:
  
jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_URL: https://www.google.com/release/foo-official-2.0.11.zip
        run: |
          filename=$(basename $RELEASE_URL)
          tag="${filename%.*}"
          info=$(cat env.txt)
          latest_tag=$(git describe --tags --abbrev=0)
          echo "$tag $latest_tag"
          gh release create "$tag" --generate-notes -n "$info" --notes-start-tag "$latest_tag"
