name: Release
on:
  workflow_dispatch:
  
jobs:
  Release-Notes:
    uses: fpe-products/PLATFORM-platform-vld-meta_data/.github/workflows/release_notes.yml@UFS-20010-align-all-platforms-repos-workflows
    with:
      tag: foo-official-2.1.2
