name: IDs
on: 
  workflow_dispatch:

jobs:
  ShowIDs:
    runs-on: ubuntu-latest
    steps:
      - name: run_id = ${{ github.run_id }}
        run: echo "run_id = ${{ github.run_id }}"
      - name: run_number = ${{ github.run_number }}
        run: echo "run_number = ${{ github.run_number }}"
      - name: run_attempt = ${{ github.run_attempt }}
        run: echo "run_attempt = ${{ github.run_attempt }}"
