name: test
on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    outputs:
      configs: ${{ steps.values.outputs.values_list }}
    steps:
      - uses: actions/checkout@v3
        
      - name: get matrix values
        id: values
        run: |
          $values = python get_dict_values.py
          echo $values
          echo "values_list=$values" >> "$GITHUB_OUTPUT"
        
  jobs2:
    needs: job1
    runs-on: windows-latest
    strategy:
      matrix:
        build_config: ${{ fromJSON(needs.job1.outputs.configs) }}
        
    steps:
      - run: |
          echo {{ matrix.build_config }}
    
