name: Test Container

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
  
    container: ghcr.io/${{ github.repository }}:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python script.py
