name: Update
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/release_pckg.yml'

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Update change
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          for branch in $(git for-each-ref refs/heads/* | cut -d"$(printf '\t')" -f2 | cut -b12-)
          do
              echo "branch=$branch"
              git checkout $branch
              git cherry-pick -x --keep-redundant-commits --strategy-option theirs ${{ github.sha }}
              git push
          done
